apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: product
  namespace: argocd
spec:
  description: Product team applications
  sourceRepos:
    - 'https://github.com/andygolubev/eks-argo-terraform'
  destinations:
    - namespace: product
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'


