# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.13"
  required_providers {
    aws        = { source = "hashicorp/aws", version = ">= 6.13" }
    helm       = { source = "hashicorp/helm", version = ">= 3.0" }
    kubernetes = { source = "hashicorp/kubernetes", version = ">= 2.38" }
  }
}

provider "aws" {
  region = "us-east-1"
}
